### ISSUE TITLE
case mismatch in the use of config-macro PAL_RTOS_64BIT_TICK_SUPPORTED

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#14]
pal_rtos.c makes use of `PAL_RTOS_64Bit_TICK_SUPPORTED` [here](https://github.com/ARMmbed/pal/blob/master/Source/PAL-Impl/Modules/RTOS/pal_rtos.c#L42). This is a case-mismatch for the actual config macro [PAL_RTOS_64BIT_TICK_SUPPORTED](https://github.com/ARMmbed/pal/blob/master/Source/PAL-Impl/Services-API/pal_configuration.h#L30) [note that BIT is upper case in the actual macro].

**Comment by NirSonnenschein** [comment]
good catch - we will fix this for the next release

**Comment by NirSonnenschein** [comment]
fixed in R.10
