### ISSUE TITLE
documentation around pal_osKernelSysTick is unclear

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#17]
Reading the [doc-header for pal_osKernelSysTick](https://github.com/ARMmbed/pal/blob/master/Source/PAL-Impl/Services-API/pal_rtos.h#L77), I could not figure out what the API was meant to return.

Tick could be an overloaded concept here. Assuming that a 'tick' refers to the interval of time between the firing of SysTick hardware interrupts, as in ARM cores, I struggled to understand whether pal_osKernelSysTick() requires returning the instantaneous value of the SysTick h/w counter or the count of 'ticks seen so far' as maintained in software by the kernel.

On many CortexM micros, the Systick is a  24-bit  down counter (hardware) running out of the core CPU clock. Is this API meant to return the value of this SysTick timer? If so, the following comment in the documentation made it confusing for me:

```
 \note this counter will wrap around very often (e.g. once every 42 sec for 100Mhz)
```

The thing about wrapping once every 42 sec at 100Mhz doesn't say much; this property is true for any 32-bit counter incrementing at 100MHz. But the SysTIck h/w counter as defined in ARM-v7 is not a 32-bit counter (it is a 24-bit counter). This adds to the confusion.

It may be that what is needed to be returned here (for ARM m-class MCUs) a combination of the 24-bit SysTick H/W counter along with lower 8 bits of the kernel's tick software counter.

I believe there is at least a source of confusion here which should be clarified. Perhaps what is meant by a `tick` needs to be clarified.

**Comment by rgrover** [comment]
Please define some bounds on what a `tick` could be. Without this, a platform porter could choose to define something as precise as a clock cycle as a `tick`, alternatively the platform porter could choose `tick` to be a very imprecise interval.

Please also clarify what this API is meant to be used for.

**Comment by mohammad1603** [comment]
Thanks for the comment, we added more information / specifications about system tick definition and its bounds in the PAL RTOS documentation.
in general this API meant to return the kernel system tick counter, regarding the implementation of the tick counter (whether h/w or s/w) it depends on the platform implementor, our requirment is to limit the lower bound to 1KHz at least.
The usage of this API is for time comparison in general.
the clarifications will be in the upcoming PAL release.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
