### ISSUE TITLE
pal_osTimerDelete() does not specify how the platform should handle active timers

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#26]
The documentation for `pal_osTimerDelete()` does not clarify the platform's behaviour when called for timers which are active.

There are two reasonable options:
- The active timer would automatically be stopped before getting deleted.
- An error should be returned to the user to indicate potential resource leak.

**Comment by NirSonnenschein** [comment]
I agree that timer delete should stop timers before deletion. I think this is the best option.
We will fix this for the next version.

**Comment by NirSonnenschein** [comment]
Mohammad checked this out, and apperantly the CMSIS API documentation guaratess that the delete funciton will stop the timer before deletion. this means that the MBED OS port should behave ok without modifications. 
We will add a delete in all ports where the delete doesn't guaranteed this behavior

**Comment by rgrover** [comment]
I don't think you should unilaterally close a bug report. I am not satisfied that the right thing has been done in this case. The documentation doesn't specify platform's behaviour when delete is called on an active timer. MbedOS might be doing the right thing, but unless the expected behaviour is documented other ports might not even know how to handle this situation.

**Comment by NirSonnenschein** [comment]
Agreed regarding documentaiton, re-opning the issue so that we dont' forget.

**Comment by mohammad1603** [comment]
We added this comment as a requirement from the platform layer, this API must stop the timer before deletion.
Thanks for the comment, the updated API will be available in the upcoming PAL release.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
