### ISSUE TITLE
errors in the API documentation for pal_osMessageGet()

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#31]
``` C++
/*! Get a Message or Wait for a Message from a Queue.
*
* @param[in] messageQID the handle for the memory pool
* @param[in] timeout timeout in milliseconds
* @param[out] event the data to send
*
* \return the function returns the status in the form of palStatus_t which will be PAL_SUCCESS(0) in case of success and one of the following error codes in case of failure:
* PAL_ERR_RTOS_RESOURCE - in case semaphore was not available but not due to time out.
* PAL_ERR_RTOS_TIMEOUT -  no message arrived during the timeout period.
* PAL_ERR_RTOS_RESOURCE -  no message received and there was no timeout
*/
palStatus_t pal_osMessageGet(palMessageQID_t messageQID, uint32_t timeout, uint32_t* messageValue);
```
- The third parameter in the API is `messageValue`. This is inconsistent with the documentation.
- In the part describing return values, there is duplicate mention of `PAL_ERR_RTOS_RESOURCE`.
- In the first instance of PAL_ERR_RTOS_RESOURCE, the document mentions `in case semaphore was not available but not due to time out.` Why is there a mention of `semaphore`? How is that related?
- What is the meaning of `no message received and there was no timeout`? When can this happen?  And how is it different from `no message arrived during the timeout period`?
- The documentation does not specify behaviour when timeout is provided as `0`.

**Comment by rgrover** [comment]
Can `pal_osMessageGet` be called from an interrupt context if timeout is 0?

**Comment by rgrover** [comment]
The documentation also does not specify if `PAL_RTOS_WAIT_FOREVER` is a valid argument for `timeout`.

**Comment by mohammad1603** [comment]
Thanks for the comment, the fix will be published in the upcoming PAL release

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
