### ISSUE TITLE
errors in the API documentation for pal_osMutexWait()

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#36]
``` C++
/*! Wait until a Mutex becomes available.
*
* @param[in] mutexID the handle for the mutex
* @param[in] millisec the timeout for the waiting operation if the 
             timeout expires before the semaphore is released and 
             error will be returned from the function, PAL_RTOS_WAIT_FOREVER can be used.
*
* \return the function returns the status in the form of palStatus_t which will be PAL_SUCCESS(0) in case of success and one of the following error codes in case of failure:
*         PAL_ERR_RTOS_RESOURCE - mutex not avaialbe but no time out set.
*         PAL_ERR_RTOS_TIMEOUT - mutex was not available until timeout expired.
*         PAL_ERR_RTOS_PARAMETER - mutex id is invalid
*         PAL_ERR_RTOS_ISR - cannot be called from interrupt service routines
*/
```
- It is not specified if a value of 0 can be used for the `millisec` parameter. Ideally, this should be possible, even from an interrupt context. The document should specify the return code if `millisec` is passed in as 0 while the mutex is acquired by another task. Is that the same as `PAL_ERR_RTOS_RESOURCE`?
- It is not specified if a mutex can be re-entrant (i.e. acquired recursively by the same thread). Having this capability usually simplifies coding for certain kinds of algorithms.
- It is not specified if (and under what conditions) this API can be used from an interrupt context.
- The documentation incorrectly mentions `semaphore`.
- There are grammatical errors in the documentation for the `millisec` parameter.

**Comment by rgrover** [comment]
If `pal_osMutexWait()` is allowed recursive operation, then the API for `pal_osMutexRelease()` may need an update to indicate when the mutex is finally released.

**Comment by rgrover** [comment]
Please note that the first of the above comments (which says 'It is not specified if a value of 0 can be used for the millisec') can be generalized to any duration which maps to less than one tick.

**Comment by rgrover** [comment]
Supporting competing notions of 'ticks' and 'milliseconds' across APIs can be confusing.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
