### ISSUE TITLE
issues with the documentation for pal_osSemaphoreWait()

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#40]
``` C++
/*! Wait until a Semaphore token becomes available.
*
* @param[in] semaphoreID the handle for the semaphore
* @param[in] millisec the timeout for the waiting operation if the timeout 
             expires before the semaphore is released and error will be 
             returned from the function, PAL_RTOS_WAIT_FOREVER can be used.
* @param[out] counteresAvailable the number of semaphore available at the call if semaphore is available, if semaphore was not available (timeout/error) zero is returned. 
* \return the function returns the status in the form of palStatus_t which will be PAL_SUCCESS(0) in case of success and one of the following error codes in case of failure:
*       PAL_ERR_RTOS_TIMEOUT - semaphore was not available until timeout expired.
*       PAL_ERR_RTOS_PARAMETER - semaphore id is invalid.
*/
palStatus_t pal_osSemaphoreWait(palSemaphoreID_t semaphoreID, uint32_t millisec, int32_t* countersAvailable);
```
- Semaphore counter is a `uint32_t` and it cannot go negative. The parameter `countersAvailable` is declared to have type `int32_t *`. This is a sign-mismatch. 
- documentation does not state if semaphores may be acquired (taken) from ISRs given a timeout value of 0 milliseconds.
- The documentation for `counteresAvailable` states: `the number of semaphore available at the call..`.  The use of the words "_at the call_" is a bit confusing. It is not stated clearly whether this output parameter will contain the value of the counter _before_, _after_, or _at the time of making_ the call. If the calling task has to block while waiting for the resource, what should the value be returned upon wakeup?
- What should `counteresAvailable` return in the case of a timeout?
- spelling mistake in the name of the parameter `counteresAvailable`. This can also be caught by looking at doxygen errors.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
