### ISSUE TITLE
imprecise types used for fields within `palSocketAddress_t`

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#42]
```C++
typedef struct palSocketAddress {
    unsigned short    addressType;    /*! address family for the socket*/
    char              addressData[PAL_NET_MAX_ADDR_SIZE];  /*! address (based on protocol)*/
} palSocketAddress_t; /*! address data structure with enough room to support IPV4 and IPV6*/
```

There are several instances of the following `if (address->addressType == PAL_AF_INET)`...

Perhaps the type for `addressType` should be `palSocketDomain_t` instead of `unsigned short`?

**Comment by rgrover** [comment]
and should `addressData` have the type `const char (*)[PAL_NET_MAX_ADDR_SIZE]`?

**Comment by rgrover** [comment]
There are internal types, `pal_socketAddressInternal_t` (for IPV4 addresses) and `pal_socketAddressInternal6_t` (for IPV6 addresses), which aren't exposed in `pal_network.h`, but which are expected to align with `palSocketAddress_t`. This alignment assumption is implicit in the following kind of code from pal_setSockAddrIPV4Addr() where 'address'  is of type `palSocketAddress_t*`:
```
pal_socketAddressInternal_t* innerAddr = (pal_socketAddressInternal_t*)address;
```
And this is the sort of thing could lead to surprises and bugs over time.

For instance, the first field of both `pal_socketAddressInternal` and `pal_socketAddressInternal6_t`  is reserved for the address family. There is an implicit assumption in the code that this would align with `addressType` of `palSocketAddress_t`. `addressType` is declared as `unsigned short`, whereas `pal_sin_family` is `short int` and `pal_sin6_family` is `uint16_t`. These types are *not* guaranteed to be identical across toolchains.

This is a toolchain relative bug waiting to jump out at us.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
