### ISSUE TITLE
pal_plat_rtos.h should add includes

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#9]
`pal_plat_rtos.h` makes use of types such as `palThreadFuncPtr` which come from headers that are not directly included. 

The only includes at the moment are:
```c++
#include "pal_configuration.h"
#include "pal_types.h"
```

This needs to be extended by includes for files like `pal_rtos.h`.

Strangely, `pal_rtos.h` resides under `Source/PAL-Impl/`. If PAL-Impl is meant for implementation specific components, then in a way this dependency of pal_plat_rtos.h on pal_rtos.h says that a platform-neutral abstraction depends on a sub-header which is implementation specific.

Please clarify.

**Comment by NirSonnenschein** [comment]
closed in R1.0
